name: MiniGameCore
version: '1.1.2.1'
main: wueffi.MiniGameCore.MiniGameCore
api-version: '1.20'
load: STARTUP
authors: [ "Waffle [ Wueffi ]" ]
description: Core Plugin for a linked MiniGame System.
depend: [ ]
commands:
  mg:
    description: Main minigame command.
    usage: /mg <subcommand>
    permission: mgcore.use
permissions:
  mgcore.use:
    default: true
  mgcore.admin:
    default: op