name: MiniGameCore
version: '1.3.7.2'
main: wueffi.MiniGameCore.MiniGameCore
api-version: '1.21'
load: STARTUP
authors: [ "Waffle [ Wueffi ]" ]
description: Core Plugin for a linked MiniGame System.
depend: [ ]
commands:
  mg:
    description: Main minigame command.
    usage: /mg <subcommand>
    permission: mgcore.use
  party:
    description: Main party command.
    usage: /party <subcommand>
    permissions: mgcore.use
  p:
    description: Alt party command.
    usage: /p <subcommand>
    permissions: mgcore.use
  teamchat:
    description: Main teamchat command.
    usage: /teamchat <message>
    permissions: mgcore.use
  tc:
    description: Alt teamchat command.
    usage: /teamchat <message>
    permissions: mgcore.use
permissions:
  mgcore.use:
    default: true
  mgcore.admin:
    default: op