name: MiniGameCore
version: '1.3.5'
main: wueffi.MiniGameCore.MiniGameCore
api-version: '1.21'
load: STARTUP
authors: [ "Waffle [ Wueffi ]" ]
description: Core Plugin for a linked MiniGame System.
depend: [ ]
commands:
  mg:
    description: Main minigame command.
    usage: /mg <subcommand>
    permission: mgcore.use
  party:
    description: Main party command.
    usage: /party <subcommand>
    permissions: mgcore.use
  teamchat:
    description: Command to chat with your team.
    usage: /teamchat <message>
    permissions: mgcore.teamchat
    aliases: ["tc"]
permissions:
  mgcore.use:
    default: true
  mgcore.teamchat:
    default: true
  mgcore.admin:
    default: op